# Generated by Django 2.2.7 on 2019-12-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191128_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='Game1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='Game2',
            field=models.DateTimeField(),
        ),
    ]
