# Generated by Django 2.2.7 on 2019-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191205_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='Game1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='Game2',
            field=models.CharField(max_length=256),
        ),
    ]
